"""Create a complete five-chapter manuscript from measured experiment artifacts."""
from pathlib import Path
import json
import re
import pandas as pd

ROOT=Path(__file__).resolve().parents[1];R=ROOT/'results';blocks=[]
def read(name):return json.loads((R/(name+'.json')).read_text())
def h(text,level=2):blocks.append({'type':'heading','text':text,'level':level})
def p(text):blocks.append({'type':'paragraph','text':text})
def table(caption,headers,rows,widths=None):blocks.append({'type':'table','caption':caption,'headers':headers,'rows':rows,'widths':widths})
def fig(file,caption,width=5.6):blocks.append({'type':'figure','path':str(R/'figures'/file),'caption':caption,'width':width})
def eq(kind,number):blocks.append({'type':'equation','kind':kind,'number':number})
def fmt(x):return f'{float(x):.4f}'
def mean_sd(series):return f'{series.mean():.4f} ± {series.std(ddof=1):.4f}'

audit=read('data_audit');split=read('split_summary');ex=read('explanation_audit');ci=read('static_uncertainty');env=read('environment')
sm=pd.read_csv(R/'static_metrics.csv');stream=pd.read_csv(R/'stream_metrics.csv');ab=pd.read_csv(R/'exploratory_ablation.csv')
rf=sm[sm.model=='Random Forest'];primary=rf[rf.seed==17].iloc[0]
ag=stream.groupby(['delay_batches','policy']).mean(numeric_only=True)
importance=pd.read_csv(R/'shap_importance.csv');cases=read('case_studies')

h('Abstract',1)
p(f'This project investigates explainable and adaptive machine learning for binary phishing detection using archived URL strings. Thirty deterministic lexical features are recomputed from the PhiUSIIL dataset. After removing {audit["duplicate_rows_removed"]:,} canonical duplicates, {audit["retained_rows"]:,} samples are divided into training, validation and test partitions with no shared registered-domain groups. Logistic Regression, a Decision Tree and a Random Forest are evaluated with validation-selected thresholds. The Random Forest achieves mean phishing F1 {rf.f1.mean():.4f} and average precision {rf.average_precision.mean():.4f} across three model seeds on the fixed test partition. TreeSHAP explanations reconstruct phishing probabilities with maximum residual {ex["max_additivity_error"]:.2e}. A separate constructed, class-balanced URL-length shift compares fixed, periodic and ADWIN-triggered forest retraining, scoring original arrival predictions under immediate and delayed labels. With immediate labels, mean stream F1 is {ag.loc[(0,"fixed"),"f1"]:.4f}, {ag.loc[(0,"periodic"),"f1"]:.4f} and {ag.loc[(0,"drift"),"f1"]:.4f}, respectively. ADWIN requires one retraining per run compared with seven periodic retrainings in this scenario. Source-bias diagnostics reveal that all legitimate benchmark URLs use HTTPS and have empty paths; a host-only exploratory forest achieves substantially lower F1 {ab[ab.variant=="host_only"].f1.mean():.4f}. The results support a reproducible integration of attribution and adaptive retraining under the stated benchmark conditions. They do not establish performance on natural temporal drift, realistic benign URL paths, or live phishing campaigns.')
p('Keywords: phishing detection; URL features; explainable machine learning; SHAP; adaptive retraining; distribution shift; delayed labels.')

h('Chapter 1. Introduction',1)
h('1.1 Background of Study')
p('Phishing detection requires a system to distinguish deceptive destinations from legitimate ones. URL-based classification offers a compact input representation: the scheme, hostname, path and query can be inspected before retrieving page content. However, patterns learned from a benchmark may reflect the way that benchmark was collected. A detector can therefore score highly while relying on cues that fail when legitimate sites or attackers change their URL structure. Ma et al. investigated large-scale online learning for malicious URLs as early as 2009, demonstrating that adaptation in this broader detection problem is established research [3].')
p('A useful undergraduate investigation should make the evidence behind detection decisions inspectable and should test what happens when the evaluation distribution changes. Explainability supplies feature-attribution evidence for a fitted prediction function. Adaptation supplies an explicit update policy when newly observed labelled examples become available. These mechanisms answer different questions: an explanation does not automatically correct a model, and a model update does not automatically produce an understandable decision. This project integrates them in a reproducible experimental pipeline while evaluating their practical limits separately.')
p('PhiUSIIL provides an accessible benchmark with raw URL strings and labels, together with URL and webpage features [1]. Its original research framework already refers to incremental learning [2]. This project uses only features recomputed from raw URL text, which keeps the prediction-time input contract explicit. It does not claim to introduce phishing adaptation, tree ensembles, SHAP, or drift detection. The intended contribution is an empirical comparison of classical detection models, attribution diagnostics and retraining policies under clearly documented conditions.')
h('1.2 Research Problem')
p('Three methodological problems motivate the study. First, related URLs from the same domain can appear in both training and test sets unless partitioning uses domain groups. Second, a high aggregate score does not reveal which feature relationships the model has learned or whether those relationships are plausible beyond the collection. Third, adaptation is often evaluated without specifying when labels become available, even though an error-based detector requires those labels. The study addresses these problems through domain isolation, tree-model attribution, source-bias diagnostics and explicit label-arrival scheduling.')
p('The research questions are: RQ1, how do linear and tree-based models perform on unseen registered domains using deterministic URL lexical features? RQ2, which features influence forest predictions, and how additive, repeatable and costly are the selected explanations? RQ3, under a constructed distribution change, how do fixed, periodic and drift-triggered retraining compare in detection performance and fitting cost when label availability is immediate or delayed?')
h('1.3 Project Aim and Objectives')
p('The project aim is to implement and critically evaluate an explainable URL-phishing detector with explicit adaptive retraining policies and reproducible experimental evidence.')
p('The objectives are to audit and document a public labelled dataset; construct URL-only features and domain-disjoint partitions; compare Logistic Regression, Decision Tree and Random Forest classifiers; inspect forest predictions using TreeSHAP and diagnose feature shortcuts; compare fixed, periodic and ADWIN-triggered retraining under identical stream inputs and label budgets; and preserve the code, configurations, predictions and report artifacts needed to reproduce the measured findings.')
h('1.4 Project Overview and Scope')
h('1.4.1 Scope',3)
p('The project is a binary supervised classification study on archived benchmark strings. The positive class is phishing. It excludes live website retrieval, HTML interpretation, DNS and WHOIS lookups, email-body detection, browser deployment and a human trust study. A batch-trained scikit-learn Random Forest is replaced with newly fitted forests when an update policy triggers; this is adaptive batch retraining rather than incremental modification of individual trees. TreeSHAP is applied to the static forest for explanation and diagnosis. It does not trigger retraining in the implemented method.')
p('Because the published dataset schema lacks per-record observation timestamps, the adaptation experiment uses a deliberately constructed sequence. It demonstrates responses to a specified distribution change, not natural chronological attack evolution. There is no claim that the conditional label distribution remains constant, and therefore the construction is not presented as a verified pure covariate shift. The first draft uses one fixed domain split, three model seeds and three paired constructed-stream realizations. A second independent corpus and repeated group partitions remain further work.')
h('1.4.2 Audience',3)
p('The primary audience is the project supervisor and assessors evaluating the research method, implementation and interpretation of evidence. The results may also help developers understand why a benchmark detector performs well and what information an adaptive update policy requires. They are not a recommendation to deploy the fitted model without independent validation.')
h('1.5 Structure of the Report')
p('Chapter 2 reviews established URL learning, tree models, prediction attribution and adaptation evaluation. Chapter 3 specifies the data processing, mathematical basis, feature contract, model configurations and experimental protocol. Chapter 4 presents implementation evidence, measured results, source-bias diagnostics and project management. Chapter 5 answers the research questions, states the supported contributions and identifies remaining limitations. Figure 1-1 connects this sequence to the evidence collected.')
fig('report_structure.png','Figure 1-1. Structure of the five-chapter project report.')

h('Chapter 2. Literature Review',1)
h('2.1 Fundamental Theories')
p('Supervised binary classification learns a function from labelled input examples and applies it to unseen observations. A predicted score can be converted into a class using a decision threshold. Classification performance depends on the input population, class balance, threshold and evaluation partition. A high score on one benchmark does not imply reliable performance on a different source. In phishing detection, false negatives leave phishing samples undetected, while false positives classify legitimate URLs as phishing. Both need to be reported rather than summarised by accuracy alone.')
p('URL lexical features represent the observed string without retrieving its destination. Counts, lengths, entropy and structural indicators are reproducible and inexpensive, but they omit the actual page and its intent. A legitimate and a phishing destination can share similar lexical patterns. Domain grouping separates registered identities across partitions; it does not eliminate similarities between campaigns, infrastructure providers or collection processes. Official grouping tools support group isolation, but actual row counts and class proportions still require auditing [11], [13].')
h('2.2 Machine Learning for URL Detection')
p('Ma et al. use lexical and host-based information in online malicious-URL learning [3]. Their study motivates updating models in a setting with changing features and large data volumes. Its task covers malicious websites more broadly and its host-based inputs include information beyond the URL string. It therefore provides historical motivation for adaptation, while its reported performance is not directly comparable with the present phishing-only benchmark.')
p('Random Forest combines randomized tree predictors and provides an established nonlinear ensemble baseline [4]. Logistic Regression supplies a regularized linear comparator, while a single tree allows a smaller nonlinear model to be inspected. Comparing these families under one feature and partition contract helps identify whether a complex model materially improves performance. No architecture is assumed to be superior before evaluation, and a static forest is not drift-aware merely because it contains many trees.')
p('Prasad and Chandra introduce the PhiUSIIL framework based on similarity index and incremental learning [2]. The creator-owned UCI record supplies the benchmark used here and identifies features derived from both URL text and webpage source [1]. The original article metadata were verified, but its full text was not accessible during this targeted review. Consequently, this report does not reconstruct its update algorithm or quote its performance. This access limitation also prevents a complete methodological comparison with that particular framework.')
h('2.3 Explainable Machine Learning')
p('Lundberg and Lee introduce SHAP as a unified additive attribution framework for individual predictions [5]. Under specified assumptions, a prediction is represented by a baseline and feature contributions. Lundberg et al. develop efficient explanations for tree models and show how local attributions can be aggregated to inspect global model behaviour [6]. These methods provide a principled way to investigate a forest without replacing its prediction function with a short verbal justification.')
p('Attributions depend on the fitted model, the output being explained and the background representation. URL length, path length, slash count and character ratios are correlated, so an interventional explainer can evaluate feature combinations that are not realistic URL strings. The sum of SHAP contributions can reproduce a probability while the causal interpretation remains unsupported. This study therefore checks numerical additivity and a limited form of repeatability, and uses explanations to identify source shortcuts. It does not infer causation, analyst usefulness or improved trust from those checks.')
p('Ahamed et al. present a recent integrated phishing evaluation involving domain-disjoint data, URL mutations and explanation stability [9]. This establishes substantial overlap with the present project in generalisation and attribution diagnostics. Their reported robustness findings are literature evidence, not results independently reproduced here. The present work focuses on a smaller reproducible pipeline and on the effect of retraining policies, simulated label delay and fitting cost. It does not claim that domain isolation or SHAP stability evaluation is novel.')
h('2.4 Adaptation and Evaluation under Change')
p('Bifet and Gavaldà introduce ADWIN, which maintains an adaptive window and tests for changes between subwindows of a monitored sequence [7]. In this project, the monitored value is the error of the original prediction after its true label becomes available. An alarm can initiate a new forest fit on recent labelled data. An error alarm does not identify the cause of change and does not prove that an adversary or a particular type of concept drift is responsible.')
p('A fixed model gives the no-update baseline. Periodic retraining updates on a predetermined schedule even without an alarm. Drift-triggered retraining updates in response to error evidence. A fair comparison keeps the base learner, original inputs, initial labelled examples and label availability equal across policies. Performance must be assessed together with update count and measured fitting cost because an update policy can improve detection while consuming additional resources.')
p('Grzenda, Gomes and Bifet examine verification latency in stream evaluation [8]. Their continuous re-evaluation approach differs from the present protocol, which scores only each sample’s original arrival prediction. River documents progressive validation with delayed target revelation [10]. These sources motivate explicit label scheduling, but neither validates an unverified dataset order. The current experiments use observation indices and simulated delays measured in batches, not calendar time or measured operational annotation latency.')
h('2.5 Research Position and Summary')
p('The reviewed sources support a research design that separates feature availability, evaluation isolation, attribution assumptions and update timing. They do not support a claim that this project introduces any of these methods. The specific contribution is a documented empirical assessment of how a common URL-feature contract behaves under domain-isolated testing, explanation diagnostics and controlled adaptive retraining. The targeted review contains foundational and directly related sources; it is not an exhaustive systematic literature review.')
p('The next chapter translates this position into executable choices. It excludes released engineered columns with uncertain derivation from the primary feature matrix, records domain partitions, fixes the main learner parameters, preserves original stream predictions and distinguishes exploratory bias diagnostics from primary comparisons.')

h('Chapter 3. Methodology',1)
h('3.1 Problem Statement and Architecture')
p('Each observation consists of an archived URL u and a binary label y. The feature extractor maps u to a 30-dimensional numerical vector x. The classifier estimates a phishing score p(y=1|x), and a threshold maps that score to a class. The static experiment assesses unseen registered domains. The adaptation experiment starts from a smaller labelled warmup set and compares how different update policies respond to a separately constructed sequence. Figure 3-1 shows the two evaluation branches and their recorded outputs.')
fig('architecture.png','Figure 3-1. Data processing, classification, attribution and adaptive evaluation architecture.')
h('3.2 Dataset and Data Processing')
p(f'The raw PhiUSIIL CSV contains {audit["raw_rows"]:,} rows: 134,850 legitimate and 100,945 phishing samples [1]. The release includes URL and webpage attributes, but this experiment reads only URL and label. Original label 0 denotes phishing and 1 denotes legitimate; the implementation maps y=1-label so that phishing is positive. The raw CSV hash is recorded in the provenance manifest, along with the repository URL, download URL, retrieval time and CC BY 4.0 licence. No destination URL in the benchmark was fetched.')
p('Canonicalisation trims surrounding whitespace, normalises scheme and authority case, and removes fragments for duplicate identification while retaining path and query case. Features are computed from the retained raw URL, including its fragment if present. Canonical duplicates with conflicting labels would be removed before selecting one retained row. Registered-domain groups use the bundled Public Suffix List in tldextract, including private suffixes. External suffix downloads are disabled; domains without a recognised suffix and IP hosts use the hostname as the group. The policy prevents sibling subdomains from silently crossing the registered-domain boundary.')
table('Table 3-1. Dataset audit and retained population.',['Audit item','Observed count'],[
 ['Raw samples',f'{audit["raw_rows"]:,}'],['Invalid samples removed',str(audit['invalid_removed'])],['Conflicting canonical URL keys',str(audit['conflicting_url_keys'])],['Canonical duplicate rows removed',str(audit['duplicate_rows_removed'])],['Retained legitimate samples',f'{audit["retained_legitimate"]:,}'],['Retained phishing samples',f'{audit["retained_phishing"]:,}'],['Registered-domain groups',f'{audit["domain_groups"]:,}']], [3.8,1.9])
p('Fitted preprocessing follows partitioning: only training data fit the Logistic Regression scaler, and only validation predictions select classification thresholds. No feature depends on labels, HTML, a legitimacy database, domain identity encoding or full-corpus target statistics. This avoids relying on released similarity and probability columns whose construction was not reproduced. It follows the principle that information unavailable at prediction time must not enter the evaluation pipeline [12].')
h('3.3 URL Feature Contract')
p('The 30 features comprise structural lengths, character ratios, entropy, host properties, delimiter counts and a fixed token count. Entropy is the Shannon entropy of character frequencies in the raw URL. Ratio denominators are guarded against zero length. Subdomain count and suffix length use the same suffix interpretation as domain grouping. The fixed token list is login, verify, account, secure, update, password, bank and signin; it was specified before the first model run. Token counts are literal substring occurrences, not natural-language or semantic understanding.')
table('Table 3-2. Definitions of the recomputed feature families.',['Family','Features and definitions'],[
 ['Lengths','URL, hostname, path, query and fragment character counts.'],
 ['Character distribution','Digit, letter and nonalphanumeric ratios; character entropy; unique-character ratio; hostname digit ratio.'],
 ['Host structure','Hostname hyphens, subdomain count and public-suffix length.'],
 ['Path and query structure','Nonempty path-segment count and ampersand-delimited query-parameter count.'],
 ['Binary indicators','HTTPS scheme, IP hostname, userinfo in authority and punycode hostname.'],
 ['Delimiter counts','Occurrences of dot, hyphen, underscore, slash, question mark, equals, ampersand, percent and at sign.'],
 ['Fixed lexical cue','Total occurrences of the eight specified substrings.']], [1.55,4.15])
h('3.4 Mathematical Basis and Model Configurations')
p('Logistic Regression uses a linear score transformed by the logistic sigmoid σ. The probability model is expressed in Equation (3-1), where w is the coefficient vector and b is the intercept. Its standardised numerical inputs are fitted within a training-only pipeline. The implementation uses L2 regularisation with C=1, balanced class weights and a maximum of 2,000 solver iterations.')
eq('logistic','3-1')
p('The Decision Tree uses a maximum depth of 10, at least five samples per leaf and balanced class weights. The Random Forest averages class probabilities from 100 trees, as represented in Equation (3-2). Its maximum depth is 16, the minimum leaf size is two, feature subsampling is the square root of the feature count, and class weights are balanced. Four worker threads are requested. These parameters are fixed primary choices; the first draft does not claim an exhaustive hyperparameter search.')
eq('forest','3-2')
p('The static experiment repeats fitting with model seeds 17, 42 and 73. All repeats use the same domain partition. Logistic Regression is effectively deterministic under this solver setting, so repeating its seed does not produce three independent data evaluations. Reported standard deviations describe model-seed sensitivity on this partition, not uncertainty over all possible populations. Random Forest is used for attribution and adaptation because it is an established tree ensemble with a compatible explainer, rather than because the holdout was used to choose an architecture.')
h('3.5 Domain Isolation and Static Evaluation')
p('StratifiedGroupKFold with five folds, shuffle enabled and split seed 20261001 assigns every registered-domain group to one fold [13]. Fold 0 is the test set, fold 1 is validation and folds 2–4 are training. This is one 60/20/20-style grouped partition, not fivefold cross-validation. Group stratification approximately preserves the observed class proportions; the actual counts are reported in Table 3-3. Pairwise domain overlap is verified as zero.')
table('Table 3-3. Fixed domain-disjoint evaluation partitions.',['Partition','Samples','Groups','Phishing'],[[s.title(),f'{v["n"]:,}',f'{v["groups"]:,}',f'{v["phishing"]:,}'] for s,v in split['partitions'].items()],[1.4,1.4,1.45,1.45])
p('For each fitted static model, the validation threshold maximises phishing F1 over thresholds returned by the precision–recall curve. The threshold is then frozen before test scoring. The procedure is identical across classifier families. It optimises a benchmark F1 objective rather than a specified deployment false-positive constraint. The test set is not used for parameter search. After primary evaluation, the observed attribution and collection patterns motivate explicitly post-hoc exploratory ablations; these do not replace or retune the primary models.')
p('The metrics are phishing precision P=TP/(TP+FP), recall R=TP/(TP+FN), F1 as in Equation (3-3), false-positive rate FP/(FP+TN), accuracy, ROC-AUC and average precision. Average precision is the noninterpolated precision–recall summary returned by scikit-learn and is reported as AP; it is not substituted for trapezoidal PR-AUC. The primary forest also receives a 200-replicate domain-group bootstrap percentile interval. Resampling entire test-domain groups preserves within-domain dependence, but the interval remains conditional on the one chosen partition.')
eq('f1','3-3')
h('3.6 Explanation Protocol')
p('TreeSHAP explains the primary forest’s phishing-class probability with an interventional background of 80 training examples. A seeded sample of 160 test observations supplies aggregate importance and timing. The baseline and feature contributions must reconstruct the same probability, as in Equation (3-4). Explanations are collected in probability units, with positive values increasing the phishing score. A shared training background and a fixed subset of 60 explained test samples are used when comparing seeds 42 and 73 with seed 17.')
eq('shap','3-4')
p('Repeatability is measured using the Spearman correlation of mean absolute feature contributions and overlap of the five highest-ranked features. This is an aggregate comparison across fitted seeds, not a full per-instance or human evaluation. Correlated features and a small explanation sample remain limitations. Three illustrative cases are selected by their actual error category and distance from the static threshold; they are diagnostic examples, not randomly representative outcomes. The report identifies them by truncated URL hash rather than publishing clickable archived phishing addresses.')
h('3.7 Constructed Stream and Adaptive Policies')
p('The stream experiment uses only the static training partition as its development pool. For each realization, a seeded shuffle selects one representative URL per domain. Within each class, short candidates have URL length at or below the 40th percentile and long candidates have length at or above the 60th percentile. Tied groups appearing in the short pool are excluded from the long pool. The generator draws a balanced 2,000-sample short warmup, 6,000 short evaluation examples in phase A and 6,000 long examples in phase B. Every phase contains 50% phishing. All warmup and evaluation domains are distinct, and no static test domain enters this stream.')
p('This label-aware construction is an offline experimental intervention. Labels determine the two class-balanced sampling strata, but are not supplied early to the learner. The intervention is designed to probe adaptation to a clear URL-length distribution change; it does not estimate the frequency, magnitude or cause of natural phishing drift. The source length percentiles are 26 and 28 characters for legitimate representatives and 28 and 35 for phishing representatives in the three completed realizations. The phase boundary is observation 6,000 after warmup, not a calendar date.')
p('All strategies begin with identical forests fitted to the same warmup data, use the same main forest parameters and apply threshold 0.5 throughout stream scoring. A batch contains 400 observations. The fixed strategy never refits. The periodic strategy refits after every four revealed batches using the most recent 4,000 labelled observations. The drift strategy monitors original-prediction binary errors with River ADWIN, delta=0.002 and its other default detector parameters. When an alarm is eligible after a two-batch cooldown, the forest is refitted on the same maximum recent-labelled window and the detector is reset. There is no refit after the final prediction because it cannot affect evaluation.')
p('At each batch, the current model first predicts every observation and records its version. Labels from batch t become usable only after predictions at batch t+d, where d is zero or two. An error stream uses the preserved original probabilities, never a replacement model’s retrospective prediction. Refitted models affect only later batches. A two-batch delay therefore represents 800 observations of simulated latency, with the exact within-batch convention stated here. Delayed labels remaining after the final prediction are not flushed into a model that will not be evaluated.')
p('The three paired stream realizations use generator seeds 427, 452 and 483 with model seeds 17, 42 and 73. Within each realization, all policies and delays see exactly the same warmup and sequence. A realization changes both the representative sample and forest seed, so cross-run variation combines those sources. Detection metrics are reported overall and separately after the boundary, along with retrain counts and measured fitting seconds. Timing is local wall-clock evidence without a production latency or memory claim.')
h('3.8 Technology and Project Management Plan')
p(f'The experiments use Python {env["python"]} on {env["platform"]}, with NumPy, pandas, scikit-learn, SHAP, River and tldextract. Fitting requests four workers. Exact versions, configuration hashes and measured outputs are retained. The report and plots are generated from the saved evidence.')
table('Table 3-4. Main experiment software versions.',['Package','Recorded version'],[[k,v] for k,v in env['packages'].items()],[3.8,1.9])
p('The initial submission milestone is 7 October 2026. Raw data, processed features, predictions and report builds are stored separately. Local version control and source checksums preserve the implementation. The local folder contains the assessment source; a hosted code link and accepted submission location remain to be arranged.')
h('3.9 Summary')
p('The method separates domain-isolated static testing from a constructed stream. Recomputed features, validation-only thresholds, original predictions and explicit label scheduling support reproducibility. Explanation and adaptation are evaluated separately, with source bias and exploratory diagnostics stated explicitly.')

h('Chapter 4. Implementation',1)
h('4.1 Implementation and Verification')
p('The implementation contains a data downloader, deterministic URL feature extractor, static and stream experiment runner, figure generator, evidence verifier and report builder. The downloader contacts the UCI repository only. The runner stores the domain manifest, numerical metrics, original predictions, retraining events and model files. The report builder reads those measured artifacts rather than embedding manually authored performance numbers. The raw data remain unchanged, and the retained proposal template is preserved separately from the generated report.')
p('An independent artifact verifier reconstructs static and stream F1/AP from saved predictions, checks confusion-matrix counts, checks pairwise domain isolation and canonical deduplication, confirms identical stream inputs across strategies, and verifies that each model version follows eligible label arrivals. SHAP reconstruction is checked numerically. Prediction CSVs are read with round-trip floating-point parsing because probability ties can otherwise change AP after serialization. These checks validate consistency with the specified protocol, not representativeness or real-world effectiveness.')
h('4.2 Static Classification Results')
table('Table 4-1. Test performance across three model seeds on one fixed domain split.',['Model','F1 mean ± SD','Recall','AP','FPR'],[[name,mean_sd(g.f1),fmt(g.recall.mean()),fmt(g.average_precision.mean()),fmt(g.false_positive_rate.mean())] for name,g in sm.groupby('model',sort=False)],[1.65,1.45,.85,.85,.9])
p(f'The Random Forest has the highest mean F1 ({rf.f1.mean():.4f}) and AP ({rf.average_precision.mean():.4f}) among these fixed configurations. Its mean recall is {rf.recall.mean():.4f}. The differences from the Decision Tree are small relative to the absolute scores. Logistic Regression is weaker on this partition but remains very high scoring. Since the three seeds share one partition and no independent corpus is included, the table does not establish a universal ranking or statistical significance between model families. Figure 4-1 shows the primary-seed precision–recall curves.')
fig('static_pr.png','Figure 4-1. Static precision–recall curves on the fixed test partition for seed 17.')
p(f'For the seed-17 forest, threshold {primary.threshold:.6f} is selected on validation. Its test confusion matrix contains {int(primary.tp):,} true positives, {int(primary.fn):,} false negatives, {int(primary.fp):,} false positives and {int(primary.tn):,} true negatives. The domain-bootstrap 95% percentile interval is [{ci["intervals"]["f1"]["lower"]:.4f}, {ci["intervals"]["f1"]["upper"]:.4f}] for F1 and [{ci["intervals"]["average_precision"]["lower"]:.4f}, {ci["intervals"]["average_precision"]["upper"]:.4f}] for AP. These conditional intervals do not include uncertainty from a different dataset or collection regime.')
fig('confusion_matrix.png','Figure 4-2. Primary forest confusion matrix on 47,031 domain-isolated test URLs.',3.6)
p(f'Mean fitting times are {sm[sm.model=="Logistic Regression"].fit_seconds.mean():.3f} seconds for Logistic Regression, {sm[sm.model=="Decision Tree"].fit_seconds.mean():.3f} seconds for the tree and {rf.fit_seconds.mean():.3f} seconds for the forest. Forest prediction over the 47,031 test rows takes approximately {rf.predict_seconds.mean():.3f} seconds in this local run. These timings include the recorded model calls and are not end-to-end deployed service latencies or repeated hardware benchmarks.')
h('4.3 Explanations and Error Cases')
p(f'The largest mean absolute attributions in the 160-example sample belong to {", ".join(importance.feature.head(5).str.replace("_"," "))}. Figure 4-3 ranks the ten leading features. The HTTPS indicator has mean absolute contribution {importance.iloc[0].mean_abs_shap:.4f} in phishing-probability units. This attribution identifies model reliance on a scheme-related cue and motivates the source-bias analysis in Section 4.5. It does not make HTTPS a universal guarantee of safety.')
fig('shap_importance.png','Figure 4-3. Mean absolute phishing-class SHAP contributions on 160 sampled test URLs.')
p(f'The maximum additivity residual is {ex["max_additivity_error"]:.2e}. Explaining 160 observations takes {ex["seconds"]:.3f} seconds, or {ex["seconds_per_explanation"]*1000:.2f} milliseconds per observation when averaged over this batch. This timing excludes explainer construction. Across the two comparison seeds, aggregate importance Spearman correlations are {ex["stability"][0]["spearman_global"]:.4f} and {ex["stability"][1]["spearman_global"]:.4f}; top-five overlaps are {ex["stability"][0]["top5_overlap"]:.2f} and {ex["stability"][1]["top5_overlap"]:.2f}. The shared background and fixed explanation subset make the comparison controlled, but only establish limited seed repeatability.')
for c in cases:
 top=c['top_features'][:3]
 desc='; '.join(f'{v["feature"].replace("_"," ")}={v["value"]:g}, attribution {v["contribution"]:+.4f}' for v in top)
 p(f'Illustrative {c["type"].replace("_"," ")} case, URL hash {c["url_sha256"][:12]}: the true label is {"phishing" if c["truth"] else "legitimate"}, the phishing score is {c["probability"]:.4f}, and the frozen threshold is {c["threshold"]:.4f}. Leading contributions are {desc}. This is a deliberately selected diagnostic example; the signed contributions describe this forest, and do not independently verify the archived site’s present status.')
h('4.4 Adaptive Retraining Results')
table('Table 4-2. Constructed-stream results averaged over three paired realizations.',['Delay','Policy','Overall F1','Phase B F1','Overall FPR','Updates'],[[str(d),{'fixed':'Fixed','periodic':'Periodic','drift':'ADWIN'}[policy],fmt(ag.loc[(d,policy),'f1']),fmt(ag.loc[(d,policy),'phase_B_f1']),fmt(ag.loc[(d,policy),'false_positive_rate']),f'{ag.loc[(d,policy),"updates"]:.0f}'] for d in [0,2] for policy in ['fixed','periodic','drift']],[.7,1.0,1.05,1.1,1.05,.8])
p(f'With immediate labels, mean overall F1 is {ag.loc[(0,"fixed"),"f1"]:.4f} for the fixed forest, {ag.loc[(0,"periodic"),"f1"]:.4f} for periodic retraining and {ag.loc[(0,"drift"),"f1"]:.4f} for ADWIN-triggered retraining. The update policies outperform the fixed model under this construction. Periodic retraining has slightly higher mean F1 than ADWIN, so the result supports similar detection performance with fewer updates rather than superior detection for the drift policy. The completed runs contain one ADWIN update and seven periodic updates each.')
p('The fixed forest has phase-B F1 0.6667 and phase-B false-positive rate 1.0000 in each realization: every long-phase legitimate observation is classified as phishing at threshold 0.5. This is a severe and deliberately constructed out-of-support failure. Its phase-B ranking AP remains high, demonstrating that ranking quality and thresholded decisions can diverge. The result cannot be interpreted as the expected failure rate of a naturally deployed detector. It instead exposes sensitivity to the warmup population and frozen score threshold.')
fig('stream_f1.png','Figure 4-4. Batch F1 through the constructed short-to-long sequence. Lines show means across three realizations; shading shows one standard deviation, not a confidence interval. The dashed line marks the designed phase boundary.')
p(f'Under a two-batch label delay, overall F1 decreases to {ag.loc[(2,"periodic"),"f1"]:.4f} for periodic retraining and {ag.loc[(2,"drift"),"f1"]:.4f} for ADWIN. Their phase-B false-positive rates average {ag.loc[(2,"periodic"),"phase_B_false_positive_rate"]:.4f} and {ag.loc[(2,"drift"),"phase_B_false_positive_rate"]:.4f}. The delayed setting requires six periodic updates and two drift-triggered updates per realization. This is consistent with a longer interval before the first useful response and a later error alarm, but the experiment does not establish that two alarms are universally optimal.')
p(f'Mean total fitting time, including initial warmup fitting, is {ag.loc[(0,"fixed"),"total_fit_seconds"]:.3f}, {ag.loc[(0,"periodic"),"total_fit_seconds"]:.3f} and {ag.loc[(0,"drift"),"total_fit_seconds"]:.3f} seconds for fixed, periodic and ADWIN policies with immediate labels. The corresponding delayed values are {ag.loc[(2,"fixed"),"total_fit_seconds"]:.3f}, {ag.loc[(2,"periodic"),"total_fit_seconds"]:.3f} and {ag.loc[(2,"drift"),"total_fit_seconds"]:.3f} seconds. ADWIN’s lower measured fitting cost is supported in these runs. Detector overhead and overall pipeline overhead are not included in the fitting-time metric, so no unmeasured total-system speedup is claimed.')
fig('stream_cost.png','Figure 4-5. Mean retraining count and total fitting time for immediate and delayed labels. Fitting time includes the initial forest but excludes detector and preprocessing overhead.')
h('4.5 Source Bias and Exploratory Feature Ablation')
p('The dataset audit reveals two strong collection patterns. All 134,850 retained legitimate URLs use HTTPS and have an empty path. Among the 100,302 retained phishing URLs, 51,623 use another scheme and 48,679 use HTTPS. Therefore scheme and path structure partly distinguish the sources in this benchmark. The patterns do not imply that legitimate browsing never contains paths or that HTTPS sites cannot phish. Domain isolation protects against identity overlap, but does not remove these collection artifacts.')
table('Table 4-3. Exploratory forest ablation on the existing test partition.',['Feature variant','Mean F1','Mean AP','Mean FPR'],[['Full 30 features',fmt(rf.f1.mean()),fmt(rf.average_precision.mean()),fmt(rf.false_positive_rate.mean())]]+[[{'without_https':'Without HTTPS flag','host_only':'Seven host features','https_only':'HTTPS flag only'}[v],fmt(g.f1.mean()),fmt(g.average_precision.mean()),fmt(g.false_positive_rate.mean())] for v,g in ab.groupby('variant',sort=False)],[2.5,1.05,1.05,1.1])
p(f'The no-HTTPS variant has mean F1 {ab[ab.variant=="without_https"].f1.mean():.4f}, compared with {rf.f1.mean():.4f} for all features. The seven-feature host-only variant reaches {ab[ab.variant=="host_only"].f1.mean():.4f}. The HTTPS-only variant reaches {ab[ab.variant=="https_only"].f1.mean():.4f}; its validation-selected threshold favours a narrower group and yields zero observed false positives at the expense of recall. Removing only the HTTPS flag does not remove path and length shortcuts. The host-only result demonstrates that the nearly perfect full-model score is not evidence that every lexical representation works equally well.')
fig('exploratory_ablation.png','Figure 4-6. Exploratory mean F1 after restricting the forest’s feature set. Ablations were designed after inspecting primary results and do not constitute an independent confirmatory test.')
p('These diagnostics were added after inspecting the original holdout and SHAP importance. Their status is exploratory, and the same holdout cannot be treated as a fresh confirmation of a revised method. The main forest and thresholds remain as originally specified. A future independent evaluation should include legitimate URLs with paths and queries, HTTPS phishing samples and a documented collection process. This would test whether the learned relationships generalise beyond benchmark shortcuts.')
h('4.6 Project Management and Deliverables')
p('The implementation has completed raw-data acquisition, feature extraction, a fixed grouped static evaluation, explanation diagnostics, eighteen paired policy-delay runs, exploratory bias ablations and evidence verification. The draft includes all five required chapters, measured tables and generated figures. Remaining work before the submission milestone concerns supervisor feedback, exact institutional report requirements, source review and any feasible additional validation. No further experiment is presented as completed until its evidence exists.')
table('Table 4-4. Revision plan leading to the initial submission milestone.',['Date','Planned work','Completion evidence'],[
 ['1 October','Complete first executable experiments and English draft','Result manifests and five-chapter report'],
 ['2–3 October','Review research questions, data bias and supervisor feedback','Revision notes and agreed scope'],
 ['4–5 October','Check robustness and feasible additional data validation','New artifacts if experiments complete'],
 ['6 October','Verify references, captions, equations and final layout','Rendered page review and checklist'],
 ['7 October','Submit the reviewed initial draft','Actual submission receipt when available']], [1.0,2.65,2.05])
p('The schedule is a revision plan, not a claim of work already completed on future dates. The student must review and understand the methods and results before submission. The exact final-report template, required length and accepted source-code submission location remain to be confirmed because the available Word file is a proposal template with internally inconsistent guidance. The present report follows its explicit typography and caption rules and the separately supplied five-chapter outline.')
h('4.7 Discussion and Summary')
p('The experiments answer complementary questions. The static result shows that the chosen feature pipeline separates the benchmark classes well across unseen domain identities. Attribution reveals a heavy reliance on scheme and structural cues. The controlled stream shows that replacing a forest with recent labelled data can repair a severe thresholded distribution failure, while label delay postpones that repair. None of these observations removes the collection bias discovered in the data.')
p('The evidence supports fewer forest fits for the ADWIN policy with performance close to periodic fitting in the tested construction. It does not support a new learning algorithm, universal detector superiority or validated natural concept-drift handling. The strongest methodological lesson is that detection scores must be interpreted together with feature availability, source structure, threshold behaviour and label timing. Those conditions determine what a numerical improvement means.')

h('Chapter 5. Conclusion',1)
h('5.1 Summary of Findings')
p(f'For RQ1, the Random Forest achieves mean phishing F1 {rf.f1.mean():.4f} and AP {rf.average_precision.mean():.4f} on the fixed domain-isolated holdout, slightly ahead of the tree and above Logistic Regression under the specified configurations. The domain-group bootstrap supplies conditional uncertainty for the primary forest. The finding demonstrates performance on this benchmark partition, not on an independently collected population.')
p('For RQ2, TreeSHAP provides additive probability attributions and highly correlated aggregate importance across three fitted seeds on a shared small sample. HTTPS, slash count and path length are leading cues. The source audit and exploratory ablations show why these cues require careful interpretation: legitimate examples in the benchmark lack realistic path variation. The explanation work is useful as a diagnostic record without claiming causal discovery or proven human benefit.')
p(f'For RQ3, both update strategies improve over the fixed warmup forest in the designed short-to-long sequence. Immediate-label ADWIN achieves mean F1 {ag.loc[(0,"drift"),"f1"]:.4f} with one refit per realization, close to periodic F1 {ag.loc[(0,"periodic"),"f1"]:.4f} with seven refits. A two-batch delay reduces performance for both. The comparison supports an update-cost tradeoff under this controlled construction; it does not demonstrate adaptation to real calendar-time drift.')
h('5.2 Contributions and Limitations')
p('The completed contribution is a reproducible integration of URL lexical classification, tree attribution, adaptive batch retraining and evidence verification. It includes an explicit positive-label mapping, canonical and registered-domain isolation, validation-only static thresholds, model and stream manifests, original-prediction label scheduling and measured fitting cost. The source-bias finding and unsuccessful fixed-model response are reported alongside the favourable results.')
p('The main limitations are one archived dataset, one grouped partition, a small sampled attribution analysis, preset rather than exhaustively tuned model configurations, a single designed shift family, artificial class balance and label delays, and local runtime measurements. The static forest and the stream policies use different training populations and threshold protocols, so their headline scores should not be compared as though they were one test. Exploratory ablations reuse the holdout and do not establish independent confirmation. Dataset labels are accepted as published; current website behaviour and annotation reliability were not independently verified.')
h('5.3 Future Work')
p('The next priority is an independent corpus with realistic legitimate paths, documented HTTPS phishing cases and, where possible, observation timestamps and label-verification times. Repeated domain partitions would expand evidence beyond the current split. Natural temporal evaluation should preserve the prediction-time feature contract and use labels only when operationally available. Different change families, threshold-only adaptation and update budgets can test whether retraining is needed to address the ranking-versus-threshold failure observed here.')
p('Further explanation work should examine sensitivity to background choice and correlated feature families, and compare successive adaptive models under a common reference set. A carefully designed user study would be needed before claiming improved analyst understanding or trust. Deployment would additionally require calibrated decisions, operating-point selection, latency measurement, error handling and monitoring on an independently validated input distribution. These are proposed extensions and are not claimed as completed components of the initial draft.')

# Reorder numeric bibliography to first citation appearance (IEEE convention).
references=json.loads((ROOT/'docs/references.json').read_text());lookup={r['number']:r for r in references};order=[]
for b in blocks:
 for text in [b.get('text',''),b.get('caption','')]:
  for num in re.findall(r'\[(\d+)\]',text):
   n=int(num)
   if n not in order:order.append(n)
mapping={old:i+1 for i,old in enumerate(order)}
for b in blocks:
 for k in ['text','caption']:
  if k in b:b[k]=re.sub(r'\[(\d+)\]',lambda m:'['+str(mapping[int(m.group(1))])+']',b[k])
def reference_text(r,num):
 authors=r['authors']
 if r['type']=='software_documentation':a=authors[0]
 else:
  def initials(name):
   words=name.split();return ' '.join(''.join(x[0]+'.' for x in w.split('-')) for w in words[:-1])+' '+words[-1]
  a=initials(authors[0])+' et al.' if len(authors)>6 else ', '.join(initials(x) for x in authors)
 text=f'[{num}] {a}, “{r["title"]},” {r["venue"]}'
 if r.get('volume'):text+=f', vol. {r["volume"]}'
 if r.get('issue'):text+=f', no. {r["issue"]}'
 if r.get('pages'):text+=f', pp. {r["pages"]}'
 if r.get('article_number'):text+=f', Art. no. {r["article_number"]}'
 if r.get('year'):text+=f', {r["year"]}'
 if r.get('doi'):text+=f', doi: {r["doi"]}'
 text+='.'
 if not r.get('doi') or r['type'] in ['dataset','software_documentation']:text+=f' [Online]. Available: {r["url"]}. Accessed: 1 October 2026.'
 return text
h('References',1)
for old in order:blocks.append({'type':'reference','text':reference_text(lookup[old],mapping[old])})
out={'title':'Explainable and Adaptive Machine Learning for Phishing Detection','author':'丁奥轩','student_id':'202318020401','major':'Software Engineering','supervisor':'Collins Sey','draft_date':'1 October 2026','status':'First draft','blocks':blocks,'citation_mapping':mapping}
(ROOT/'build/manuscript.json').write_text(json.dumps(out,indent=2,ensure_ascii=False),encoding='utf-8')
md=['# '+out['title'],'','Author: 丁奥轩 | Student ID: 202318020401 | Supervisor: Collins Sey','', 'First draft prepared 1 October 2026.','']
for b in blocks:
 if b['type']=='heading':md.append('#'*b['level']+' '+b['text'])
 elif b['type'] in ['paragraph','reference']:md.append(b['text'])
 elif b['type']=='figure':md.extend(['!['+b['caption']+']('+b['path']+')',b['caption']])
 elif b['type']=='equation':md.append('Native Word equation '+b['number']+' ('+b['kind']+')')
 elif b['type']=='table':md.extend([b['caption'],'| '+' | '.join(b['headers'])+' |','| '+' | '.join(['---']*len(b['headers']))+' |']+['| '+' | '.join(row)+' |' for row in b['rows']])
 md.append('')
(ROOT/'thesis/manuscript.md').write_text('\n'.join(md),encoding='utf-8')
words=sum(len(re.findall(r'\b[\w’-]+\b',b.get('text',''))) for b in blocks if b['type']=='paragraph')
(ROOT/'build/manuscript_stats.json').write_text(json.dumps({'prose_words':words,'figures':sum(b['type']=='figure' for b in blocks),'tables':sum(b['type']=='table' for b in blocks),'references':len(order)},indent=2))
print('Manuscript prose words:',words,'blocks:',len(blocks),'references:',len(order))
