"""Write the revised thesis from the completed audited run, never expected results."""
from pathlib import Path
import argparse,json,re
from datetime import date
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser();parser.add_argument('--run-id',required=True);args=parser.parse_args()
RUN=ROOT/'experiments'/args.run_id;R=RUN/'artifacts';FIG=RUN/'analysis/figures'
manifest=json.loads((RUN/'manifest.json').read_text());assert manifest['status']=='completed'
assert json.loads((RUN/'verification.json').read_text())['hashes_verified']
BUILD=ROOT/'build/revision_20261006';BUILD.mkdir(exist_ok=True);blocks=[]
def j(name):return json.loads((R/(name+'.json')).read_text())
def h(text,level=2):blocks.append({'type':'heading','text':text,'level':level})
def p(text):blocks.append({'type':'paragraph','text':text})
def eq(number):blocks.append({'type':'equation','number':number,'omml':str(ROOT/'thesis/equations'/f'eq_{number}.omml')})
def table(caption,headers,rows,widths):blocks.append({'type':'table','caption':caption,'headers':headers,'rows':rows,'widths':widths})
def fig(file,caption,width=5.65):blocks.append({'type':'figure','path':str(FIG/file),'caption':caption,'width':width})
def f(x):return f'{float(x):.4f}'
def sci(x):return f'{float(x):.2e}'
audit=j('data_audit');split=j('split_summary');extaudit=j('external_data_audit');ex=j('explanation_audit')
sm=pd.read_csv(R/'static_metrics.csv');em=pd.read_csv(R/'external_metrics.csv');rm=pd.read_csv(R/'replay_metrics.csv');ab=pd.read_csv(R/'exploratory_ablation.csv')
rf=sm[sm.model=='Random Forest'];full=em[em.variant=='full_30_features'];host=em[em.variant=='host_only_7_features'];ag=rm.groupby(['scenario','delay_batches','policy']).mean(numeric_only=True)
def a(delay,policy,key,scenario='source_switch'):return float(ag.loc[(scenario,delay,policy),key])
source_ci=j('static_uncertainty')['intervals'];external_ci=j('external_uncertainty');scenarios=j('replay_scenarios')
hold=extaudit['partitions']['external_holdout'];adapt=extaudit['partitions']['adaptation'];primary=rf[rf.seed==17].iloc[0]

h('Abstract',1)
p(f'This study evaluates explainable and adaptive machine learning for phishing detection using two public corpora of archived URL records. Thirty deterministic lexical features are extracted from PhiUSIIL, and Logistic Regression, Decision Tree and Random Forest classifiers are assessed on a registered-domain-disjoint source holdout. The Random Forest reaches mean phishing F1 {rf.f1.mean():.4f} and average precision {rf.average_precision.mean():.4f} across three fitting seeds. However, a frozen-model test on {hold["n"]:,} eligible Wangchuk corpus URLs from disjoint domains gives F1 {full.f1.mean():.4f}, average precision {full.average_precision.mean():.4f}, and legitimate-URL false-positive rate {full.false_positive_rate.mean():.4f}. TreeSHAP and feature ablations identify dependence on scheme and path cues that are strongly associated with the PhiUSIIL collection. An additional experiment replays unchanged records from the two sources in controlled orders, comparing a fixed forest, periodic refitting, ADWIN-triggered refitting and threshold-only updating. With immediate labels, periodic and ADWIN policies achieve mean source-switch F1 {a(0,"periodic","f1"):.4f} and {a(0,"drift","f1"):.4f}, respectively, compared with {a(0,"fixed","f1"):.4f} for the fixed forest. ADWIN uses fewer refits but gives lower detection performance than periodic updating. Delayed-label runs enforce prediction-version provenance, and a stationary-mixture control tests unnecessary update behaviour. The findings demonstrate that a near-perfect within-corpus result can coexist with severe external failure. Adaptive retraining improves this controlled replay, but the study does not establish reliable deployment or natural chronological drift handling.')
p('Keywords: phishing detection; URL classification; SHAP; domain-disjoint evaluation; external validation; adaptive retraining; delayed labels.')

h('Chapter 1. Introduction',1)
h('1.1 Background of Study')
p('Phishing detection aims to distinguish deceptive destinations from legitimate services. A URL classifier can inspect the scheme, hostname, path and query before a destination is retrieved. This offers a lightweight input contract, but the string alone cannot determine the intention or current content of a website. Online malicious-URL learning has been studied for many years: Ma et al. used lexical and host-based information to investigate scalable, changing URL populations [3]. The practical question is therefore not simply whether a classifier can obtain a high benchmark score, but whether the evidence supports its use beyond the collection that produced that score.')
p('The present study begins with PhiUSIIL, a publicly available dataset containing raw URL strings, labels, and precomputed URL and webpage attributes [1]. Its original framework already includes incremental learning in its scope [2]. Only features recomputed from the raw URL are used here. The analysis then introduces a separately published corpus by Wangchuk, containing legitimate Common Crawl URLs and phishing URLs from PhishTank [14]. The second corpus provides an opportunity to test the transfer of a frozen detector without using its labels to select the detector or its threshold.')
p('Explainability and adaptation address different parts of this problem. Feature attribution can expose a model’s reliance on collection-specific cues, while an update policy determines how the model uses newly verified examples. An explanation cannot establish that a cue is causal, and a retraining event cannot establish that the resulting decision is correct. The study therefore evaluates attribution, external generalisation and label-aware updating with separate measurements and explicit information boundaries.')
h('1.1.1 Research Problem',3)
p('An apparently strong source result can arise when train and test samples share collection conventions even after their registered domains have been separated. In this study, all retained legitimate PhiUSIIL records have HTTPS and empty paths, whereas the eligible legitimate external records usually contain paths. This creates a direct challenge to the source model’s learned representation. The external test is an assessment of that challenge, rather than an assumption that the source score transfers.')
p('The research questions are: RQ1, how do classical URL classifiers perform on a domain-isolated source test and an independently held-out portion of a second corpus? RQ2, what do TreeSHAP, seed-repeatability checks and feature ablations reveal about the detector’s learned cues? RQ3, when unchanged records from the two corpora are replayed in a controlled source switch, how do refitting and threshold-update policies compare under immediate and delayed labels, and what happens in a stationary-mixture control?')
h('1.2 Project Aim')
p('The project aim is to implement and critically evaluate an explainable URL-phishing classification pipeline with adaptive update policies, using reproducible evidence to determine the limits of detection across dataset sources.')
h('1.3 Project Objectives')
p('The first objective is to acquire public URL datasets, preserve their provenance and published labels, and audit duplicates, malformed records and domain overlap. The second objective is to compare linear and tree-based classifiers under a documented source split and then freeze the selected model configurations and thresholds before external scoring.')
p('The third objective is to explain the source forest using TreeSHAP, check numerical additivity and limited seed repeatability, and diagnose feature dependence through clearly identified exploratory ablations. The fourth objective is to compare fixed, periodic, drift-triggered and threshold-only policies on identical replay records with explicit label timing and model-version tracking. The final objective is to retain the code, configurations, model checkpoints, predictions and verification records that allow the reported findings to be inspected and reproduced.')
h('1.4 Project Overview')
p('The pipeline contains a source-training branch, an external frozen-model test and an adaptive replay branch. The source branch establishes a benchmark result and its explanations. The external branch evaluates transfer to unseen domains from another published corpus. The replay branch supplies labels only after each original prediction and measures whether subsequent updates improve later decisions. All numerical results in Chapter 4 are computed from the retained execution archive.')
h('1.4.1 Scope',3)
p('The task is binary classification of archived URL strings, with phishing positive. No listed page is fetched; HTML, DNS, WHOIS and live security feeds are excluded. Published labels are adopted without independently reverifying present-day site behaviour. Adaptive updates replace a batch-trained forest or adjust its threshold; they do not incrementally modify individual trees.')
p('The replay uses real archived records and unchanged labels. Order, source boundaries and label delay are experimental choices because observation and verification timestamps are unavailable. A stationary control shuffles the same record pool. These controlled comparisons do not establish natural-time drift frequency or magnitude.')
h('1.4.2 Audience',3)
p('The findings are intended for researchers and developers assessing URL detectors and for academic assessors examining the implementation and evidence. The pipeline supports investigation of benchmark shortcuts and update tradeoffs. The measured external false-positive rate rules out treating the source-trained full-feature forest as a reliable operational detector.')
h('1.5 Structure of the Report')
p('Chapter 2 reviews the relevant learning, attribution and adaptation literature. Chapter 3 defines the model, datasets, information boundaries and evaluation protocols. Chapter 4 reports measured results, diagnostics and implementation verification. Chapter 5 answers the research questions and sets out limitations and future work. Figure 1-1 summarises this structure.')
fig('figure_1_1_structure.png','Figure 1-1. Structure of the project report.',4.9)

h('Chapter 2. Literature Review',1)
h('2.1 Fundamental Theories')
p('A supervised binary classifier maps an observed feature vector to a score and applies a decision threshold to predict a class. Ranking measures and thresholded measures capture different behaviours. Precision measures the fraction of phishing predictions that are labelled phishing, while recall measures the fraction of labelled phishing records detected. A false-positive rate concerns legitimate records and is particularly important when unnecessary warnings are costly. Accuracy alone can conceal these distinctions.')
p('Generalisation depends on the population represented by the evaluation set. Separating registered domains prevents the same chosen domain identity from occurring in source training and testing, but does not remove shared collection procedures or campaign-level similarities. Group-based splitting tools provide a mechanism for isolation [11], [13]; the actual grouping policy, sample counts and overlap must still be audited. A second corpus adds a different challenge, although common public feeds can create overlap and source dependence between published datasets.')
h('2.2 Background Review of Phishing Detection')
h('2.2.1 Classical and Online URL Learning',3)
p('Ma et al. studied online learning for malicious URLs using lexical and host-based information [3]. The work provides a historical basis for adaptation and scalable URL classification, but its broader malicious-site task and external host information differ from the raw-string phishing task considered here. Its reported performance is consequently not a directly comparable baseline. The PhiUSIIL framework by Prasad and Chandra also explicitly includes incremental learning [2]. The present project does not claim to introduce adaptation to URL detection.')
p('Random Forest is an established ensemble of randomized tree predictors [4]. It supplies a nonlinear comparator to regularized Logistic Regression and a single Decision Tree. These model families are useful for a controlled undergraduate study because their feature requirements and fitted predictions can be inspected. Their comparison must use the same input and split definitions. A model-family name does not imply robustness to changed sources, and the batch implementation requires an explicit update policy.')
p('The original PhiUSIIL article’s bibliographic metadata were verified, but its full text was not available during this review. This report therefore uses the creator’s dataset record for data provenance and does not assert the original paper’s detailed update algorithm or performance. That access limitation constrains the comparison with the original framework; it is not filled by inferred or copied secondary descriptions [1], [2].')
h('2.2.2 Explainable Tree Models',3)
p('Lundberg and Lee formulate SHAP as an additive feature-attribution framework for individual model predictions [5]. Lundberg et al. develop efficient tree-model explanations and connect local contributions with global inspection [6]. This provides a basis for identifying which numerical inputs contribute to a forest score. Aggregated attribution magnitudes can expose dependence on a feature family, but the signs and magnitudes remain properties of the fitted model and the selected explanation assumptions.')
p('The URL representation contains correlated quantities, including total length, path length, delimiter counts and character ratios. Interventional SHAP uses a background distribution to evaluate feature contributions and may combine feature values in ways that do not correspond to a valid URL. Numerical reconstruction is therefore an implementation check, not proof of causal meaning. The current evaluation includes additivity, a shared-background seed comparison and a small set of diagnostic cases, rather than a claim of improved human trust.')
h('2.2.3 Drift Detection and Delayed Feedback',3)
p('ADWIN maintains an adaptive window and tests whether parts of a monitored stream have different means [7]. When the monitored value is a classification error, the error can only be constructed after the relevant label is known. An alarm identifies evidence of change in the monitored sequence; it does not independently determine whether the cause is changed class prevalence, different sources, adversarial behaviour or a changed conditional label relation.')
p('Grzenda, Gomes and Bifet show why verification latency matters for data-stream evaluation [8]. Their continuous re-evaluation formulation is not identical to this study’s scoring of each original arrival prediction. River’s progressive-evaluation documentation also makes delayed target revelation explicit [10]. These sources motivate recording prediction and label-arrival events. After a refit, errors produced by an earlier model should not silently populate a detector that is being interpreted as monitoring the current model. The revised implementation enforces this provenance boundary.')
h('2.2.4 Dataset Bias and Evaluation Protocols',3)
p('Ahamed et al. report an integrated phishing evaluation involving domain-disjoint partitioning, URL perturbations and SHAP stability [9]. Their publisher and DOI metadata were rechecked, and the paper provides related evaluation context. Its measurements are not independently replicated in this project. This overlap also means that neither domain isolation nor SHAP stability can be claimed as a novel contribution here.')
p('The Wangchuk corpus is published separately from PhiUSIIL and provides raw URL and label columns under CC BY 4.0 [14]. Its legitimate class comes from Common Crawl and includes page paths. However, separate publication does not guarantee independent sources: the phishing component uses PhishTank, and the two corpora have substantial domain overlap. The current external protocol removes overlap against the complete source corpus before dividing external domains into evaluation and adaptation subsets. It also reports the resulting concentration of many legitimate URLs in relatively few domains.')
h('2.3 Gaps in the Existing Literature and Research Position')
p('The selected literature establishes URL learning, tree attribution, group isolation and drift detection. It does not establish that a particular combination will generalise across the two corpora used here. The focused research opportunity is an empirical comparison that connects source-domain performance to a frozen external test and then assesses update policies with realistic information ordering. This is an integration and evaluation contribution, not a claim of a new classifier, new attribution algorithm or comprehensive literature coverage.')
table('Table 2-1. Relationship between selected prior work and this study.', ['Work','Relevant contribution','Boundary for this study'],[
 ['Ma et al. [3]','Online malicious-URL learning','Different task and host-based inputs'],
 ['Prasad and Chandra [2]','PhiUSIIL and incremental-learning scope','Original full text not inspected'],
 ['Lundberg et al. [5], [6]','Additive and tree-model attribution','Attribution does not establish causation'],
 ['Bifet and Gavaldà [7]','Adaptive-window change detection','An alarm does not prove useful retraining'],
 ['Grzenda et al. [8]','Verification-latency evaluation','Original-arrival scoring used here'],
 ['Ahamed et al. [9]','Domain and explanation evaluation','Findings not reproduced here']], [1.3,2.0,2.4])
h('2.4 Summary')
p('The evidence supports explicitly separating model fitting, explanation assumptions, source transfer and feedback timing. The next chapter defines those boundaries before reporting results. The review remains targeted; a broader systematic review and independent replication of related papers would be necessary for stronger novelty or state-of-the-art claims.')

h('Chapter 3. Methodology',1)
h('3.1 Problem Statement')
p('For each archived URL u, a deterministic extractor produces a 30-dimensional feature vector x. The target y equals 1 for phishing and 0 for legitimate. The source models are fitted using PhiUSIIL training labels, their thresholds are selected on source validation, and their predictions are evaluated on source and external holdouts. The adaptive branch begins from a smaller warmup sample and predicts each replay batch before the corresponding labels may be used. All policies receive identical records and label schedules within each realization.')
h('3.2 Approach')
h('3.2.1 Mathematical Basis',3)
p('Logistic Regression transforms a linear score using the sigmoid in Equation (3-1), where w is a coefficient vector and b is the intercept. A training-only StandardScaler precedes the estimator. The implementation uses L2 regularisation with C=1, balanced class weights and at most 2,000 solver iterations. These are fixed configurations, not the outcome of an exhaustive hyperparameter search.')
eq('3-1')
p('The Decision Tree uses a maximum depth of 10, at least five samples per leaf and balanced class weights. The Random Forest averages the tree class scores as in Equation (3-2), with B=100 trees, maximum depth 16, minimum leaf size two and square-root feature subsampling. Four workers are requested. The forest scores are treated as model outputs; probability calibration has not been independently validated.')
eq('3-2')
p('Precision P, recall R, F1 and false-positive rate are defined in Equation (3-3). The confusion counts are computed with phishing positive. Zero-denominator precision or recall is assigned zero by the implementation. The report also records accuracy, ROC-AUC and average precision, so thresholded detection is not conflated with ranking performance.')
eq('3-3')
p('Average precision is calculated using Equation (3-4), where thresholds are traversed from highest to lowest score, tied scores are grouped, the initial recall is zero, and each term weights precision by its increase in recall. This is the noninterpolated AP summary rather than trapezoidal PR-AUC. As the threshold includes all observations, recall becomes one and precision equals the positive-class prevalence. That endpoint explains the right-hand drop in a high-scoring PR curve [15].')
eq('3-4')
p('SHAP represents the explained score by a baseline and feature contributions, as in Equation (3-5). Here M=30 and f is the phishing-class forest score. Equation (3-6) expresses the Shapley contribution of feature j over subsets S of the feature set F. The value v(S) averages the model output with the explained observation’s features in S fixed and the remaining features drawn from the training background. This interventional attribution does not estimate a phishing cause [5], [6].')
eq('3-5');eq('3-6')
p('For observation i in batch b(i), the binary error and batch-level label arrival are written in Equation (3-7). The original prediction is retained, and its label becomes available only after prediction at the scheduled arrival batch. ADWIN tests a subwindow-mean difference against its internally computed threshold, represented schematically in Equation (3-8). The threshold depends on the configured significance level and current window statistics; this expression is not a substitute implementation of ADWIN’s detailed bound. River’s implementation uses delta=0.002 and its other recorded-version defaults [7].')
eq('3-7');eq('3-8')
h('3.2.2 Overview of Model Architecture',3)
p('Figure 3-1 shows the information flow. Fitting and threshold selection finish using source data before frozen external scoring. The external corpus is first audited and divided by registered domain into a held-out evaluation subset and an adaptation pool. The adaptation pool can supply labels to the replay branch; the external holdout is excluded from all replay fitting and threshold updates. TreeSHAP explains the static source forest, while saved replay model checkpoints make the adaptive predictions inspectable.')
fig('figure_3_1_architecture.png','Figure 3-1. Source fitting, external evaluation and controlled adaptive replay.')
h('3.2.3 Dataset and Data Processing',3)
p(f'PhiUSIIL contains {audit["raw_rows"]:,} raw records, comprising 134,850 legitimate and 100,945 phishing URLs [1]. Original labels 1 and 0 are mapped to experimental labels 0 and 1 respectively. The downloaded file is preserved with its SHA-256 checksum. Canonicalisation trims outer whitespace, normalises scheme and authority case, and removes the fragment for duplicate identification while retaining path and query case. The feature extractor operates on the retained original string. {audit["duplicate_rows_removed"]:,} canonical duplicate rows are removed, leaving {audit["retained_rows"]:,} observations and {audit["domain_groups"]:,} registered-domain groups. No conflicting canonical labels or missing/unparsable-host exclusions occur in this source pass.')
p('Domain grouping uses tldextract with its bundled Public Suffix List, private suffixes enabled and external suffix downloads disabled. Unknown suffixes and IP addresses fall back to the hostname. A group therefore approximates a registered administrative identity, rather than a full URL or arbitrary subdomain. The choice does not remove every possible relationship between campaigns or providers. No domain identity, published label, webpage feature or full-corpus target statistic is included as a classifier input.')
p('The 30 numerical features comprise URL, host, path, query and fragment lengths; digit, letter and nonalphanumeric ratios; character entropy and unique-character ratio; host digit ratio and hyphens; subdomain and path-segment counts; suffix length and query-parameter count; HTTPS, IP-host, userinfo and punycode indicators; nine delimiter counts; and occurrences of the fixed substrings login, verify, account, secure, update, password, bank and signin. These definitions use information in the observed string. Fitted transformations, including the logistic scaler, use source training data only [12].')
table('Table 3-1. Source data audit and fixed evaluation partitions.', ['Population','URLs','Domain groups','Phishing'],[
 ['Retained PhiUSIIL',f'{audit["retained_rows"]:,}',f'{audit["domain_groups"]:,}',f'{audit["retained_phishing"]:,}']]+[[name.title(),f'{v["n"]:,}',f'{v["groups"]:,}',f'{v["phishing"]:,}'] for name,v in split['partitions'].items()],[2.0,1.2,1.3,1.2])
p('The Wangchuk V1 corpus contains 149,726 raw rows with columns URL and Label [14]. The numeric class counts match the creator’s published totals: label 0 has 94,919 legitimate records and label 1 has 54,807 phishing records. This supports the adopted mapping, although the landing-page description does not separately spell out the numeric encoding. The raw file’s checksum matches the repository metadata. Individual labels and present-day website behaviour are not independently verified.')
p(f'External preprocessing applies no relabelling or class-specific repair. Missing or unparsable hosts and strings containing whitespace, angle brackets or double quotes are excluded; other observed characters are retained. The audit removes {sum(extaudit["quality_excluded_by_class"].values()):,} quality-flagged rows and {extaudit["duplicate_rows_removed"]:,} canonical duplicates, with no conflicting canonical keys. Registered-domain overlap with any part of PhiUSIIL removes {sum(extaudit["source_domain_overlap_excluded_by_class"].values()):,} more records. Table 3-2 reports the resulting subsets, rather than attributing results to the entire external release.')
table('Table 3-2. External audit and domain-disjoint subsets.', ['Stage or subset','Legitimate','Phishing','Total'],[
 ['Raw Wangchuk corpus','94,919','54,807','149,726'],
 ['Quality exclusions',str(extaudit['quality_excluded_by_class']['0']),str(extaudit['quality_excluded_by_class']['1']),str(sum(extaudit['quality_excluded_by_class'].values()))],
 ['Canonical duplicates','20,106','170',f'{extaudit["duplicate_rows_removed"]:,}'],
 ['Source-domain exclusions',f'{extaudit["source_domain_overlap_excluded_by_class"]["0"]:,}',f'{extaudit["source_domain_overlap_excluded_by_class"]["1"]:,}',f'{sum(extaudit["source_domain_overlap_excluded_by_class"].values()):,}'],
 ['External holdout',f'{hold["legitimate"]:,}',f'{hold["phishing"]:,}',f'{hold["n"]:,}'],
 ['Adaptation pool',f'{adapt["legitimate"]:,}',f'{adapt["phishing"]:,}',f'{adapt["n"]:,}']], [2.4,1.1,1.1,1.1])
p(f'GroupShuffleSplit with seed 61006 assigns half the remaining groups to the external holdout and half to adaptation [11]. Both subsets contain 9,683 groups, but their row counts differ. The holdout contains {hold["legitimate_groups"]} groups with legitimate records and {hold["phishing_groups"]:,} groups with phishing records; a few groups contain both labels, so these class-specific counts need not sum to the total. Legitimate observations are concentrated in relatively few groups. Accordingly, the external report includes domain-macro class recall and a domain-group bootstrap, in addition to row-weighted metrics. The eligible legitimate holdout has nonempty paths in {hold["legitimate_nonempty_path_fraction"]*100:.2f}% of records, contrasting with zero in the source legitimate class.')
h('3.2.4 Static and External Evaluation Protocol',3)
p('The source split uses five-fold StratifiedGroupKFold, shuffled with seed 20261001 [13]. Fold 0 is test, fold 1 validation, and folds 2–4 training. This is one fixed grouped partition, not a fivefold cross-validation estimate. Models use fitting seeds 17, 42 and 73 on that same partition. A separate Random Forest sensitivity analysis uses split seeds 481 and 902 with model seed 17; these overlapping partitions are reported descriptively and are not treated as independent studies.')
p('For each static fit, a threshold maximising phishing F1 is selected from source validation predictions and then frozen. The same rule applies to all three classifier families. Hyperparameters remain fixed. Source test and external holdout labels do not select these thresholds. The primary frozen external comparison evaluates both the full 30-feature forest and an already specified seven-feature host-only diagnostic, with each variant’s source-validation threshold. The host-only features are host length, host digit ratio, host hyphens, subdomain count, suffix length, IP-host and punycode indicators.')
p('The original feature ablations were motivated by source results and are exploratory. Their configurations were fixed before the new external scores were computed, but they do not constitute proof that all feature choices were preregistered. The full-model external result is retained even when a diagnostic variant performs better. A 200-replicate bootstrap resamples whole test-domain groups for the primary forest, separately on source and external holdouts. These intervals remain conditional on the chosen corpus and subset definitions.')
h('3.2.5 Explanation Protocol',3)
p('The seed-17 source forest is explained using an interventional training background of 80 examples. A seeded sample of 160 source-test URLs supplies global mean absolute contributions and a timed explanation batch. The maximum residual between the forest score and the SHAP baseline-plus-contributions is checked. For aggregate repeatability, seeds 42 and 73 are explained on the same 60-example subset and shared background, then compared with seed 17 using Spearman rank correlation and top-five overlap. This limited check concerns seed variation on one split; it is not a test of all local explanations, background choices, causal fidelity or user understanding.')
h('3.2.6 Controlled Replays and Feedback Timing',3)
p('The source-switch replay draws a balanced 2,000-URL warmup from unique PhiUSIIL training domains. Its first evaluation segment contains new source-domain representatives; its second contains unchanged URLs from the external adaptation pool. The three source-segment sizes are 5,200, 6,000 and 6,800, followed by 6,800, 6,000 and 5,200 target records respectively. This keeps each evaluation sequence at 12,000 observations while changing the source boundary’s alignment with a periodic schedule. Each segment is balanced by the published label. The use of labels to construct experimental strata is separate from when those labels are revealed to the learner.')
p('Target URLs are sampled without replacement, but their registered domains may repeat, reflecting the external corpus’s concentration. The stationary-mixture control pools the same warmup and evaluation records, draws a new balanced warmup and shuffles the remainder. It therefore provides a mixed-distribution control, with possible domain recurrence between its warmup and stream. Within either scenario, all policies share exactly the same warmup, sequence, fitting seed and label delay. No external-holdout domain enters either replay. The record order is constructed and cannot be reported as an observed timeline.')
p('A batch contains 400 URLs. The model first predicts the whole batch and stores scores, the applied threshold and model version. With delay d=0, labels are revealed after those predictions; with d=2, they arrive after prediction two batches later. Thus “immediate” feedback is immediate after the batch, not after each individual URL. All performance metrics use original predictions. Newly arrived labels can enter the recent training/calibration window, which contains at most 4,000 records. Future labels are inaccessible to every policy.')
table('Table 3-3. Policies compared on identical replay records.', ['Policy','Trigger','Update'],[
 ['Fixed','None','Warmup forest and threshold 0.5 retained'],
 ['Periodic','Every four revealed batches','Refit forest on recent labelled window'],
 ['ADWIN','Eligible current-model error alarm','Refit forest; reset detector; two-batch cooldown'],
 ['Threshold only','Every four revealed batches','Select recent-window F1 threshold; retain forest']], [1.05,2.0,2.65])
p('A detector reset introduces a model-version boundary. The revised ADWIN policy accepts an error only if its stored prediction version matches the current forest. Delayed errors from an older forest are excluded from that reset detector, while their labels remain eligible for training. This removes a defect in the earlier implementation, which admitted old-model errors into a new detector. The correction is covered by a small call-site test and by the recorded label-arrival ledger. Updates after the last evaluated prediction are omitted because they cannot influence any reported decision.')
p('Three fitting seeds and three corresponding record draws are evaluated for each of two scenarios, two delays and four policies, giving 48 replay runs. Cross-run variability combines draw, boundary-position and fitting-seed differences. Paired policy comparisons use the same realization. The report provides overall and second-segment F1, false-positive rates, model-refit counts and measured forest fitting time. The threshold-only policy has separate cutoff-update counts. Fitting time excludes checkpoint writing, prediction, drift detection and calibration; it is not a measurement of production service latency.')
h('3.3 Technology')
p(f'The accepted run uses an Apple M2 CPU with 24 GiB memory, Python {manifest["environment"]["python"]} on {manifest["environment"]["platform"]}. Numerical processing uses NumPy and pandas; scikit-learn implements the classifiers; SHAP supplies TreeSHAP; River supplies ADWIN; and tldextract supplies domain parsing. Exact versions are recorded in Table 3-4. No GPU training is used. LaTeX equations are converted to editable Word mathematics and placed in the template’s borderless two-column layout.')
table('Table 3-4. Software versions in the accepted experiment archive.', ['Package','Version'], [[k,v] for k,v in manifest['environment']['packages'].items()],[3.8,1.9])
h('3.4 Project Version Management Plan')
p(f'The accepted execution is stored under experiments/{args.run_id}. Its manifest records the command, start and finish times, raw-data checksums, source/configuration snapshots, software versions and output hashes. Numerical outputs include original predictions, split and replay manifests, label arrivals, update events and fitted model checkpoints. The original execution was imported into a separately labelled legacy snapshot rather than assigned a new historical run timestamp. A failed revision-run finalisation is also retained and is not used as the accepted run.')
p('Source and derived artifacts remain distinguishable. The raw dataset files are immutable inputs; cleaning policies and excluded counts are documented. A verifier independently reconstructs AP from tied-score groups, checks confusion counts and model versions, and samples saved checkpoints to reproduce recorded probabilities. Bibliographic metadata, source access dates and persistent identifiers are stored separately from the experimental data.')
h('3.5 Summary')
p('The protocol separates source testing, frozen external evaluation and controlled adaptation. Its main protections are explicit label semantics, registered-domain isolation, fixed thresholds for external scoring, unchanged archived records, version-aware delayed feedback and retained execution evidence. The following chapter reports both the favourable source results and the external failure.')

h('Chapter 4. Implementation',1)
h('4.1 Implementation and Numerical Verification')
p('The implementation contains acquisition, extraction, experiment, verification, plotting and document-generation scripts. The source branch recomputes lexical features and fits the three classifiers. The external branch rejects recorded quality flags and domain overlaps before assigning holdout and adaptation roles. The replay branch records predictions before revealing labels and persists model versions. Dataset destinations are not fetched. Configuration and source snapshots allow an independent reader to distinguish an executed condition from a proposed extension.')
p('The accepted run is verified against raw, source and artifact hashes. Nine source metric rows, six frozen external rows and 48 replay rows are checked against saved predictions. AP is recomputed independently by sorting scores and grouping ties, rather than trusting the same metric call used by training. The maximum difference is at floating-point rounding scale. In addition, 660 sampled probabilities are reconstructed from saved replay checkpoints and their original feature records. These tests establish consistency with the implemented protocol. They do not independently verify the authors’ URL labels or prove that the datasets represent deployment traffic.')
h('4.2 Source Classification Results')
table('Table 4-1. Source-holdout performance on the fixed domain split.', ['Model','Mean F1','SD of F1','Recall','AP'],[[name,f(g.f1.mean()),sci(g.f1.std(ddof=1)),f(g.recall.mean()),f(g.average_precision.mean())] for name,g in sm.groupby('model',sort=False)],[1.75,1.0,1.0,1.0,.95])
p(f'The Random Forest has mean source F1 {rf.f1.mean():.4f} and AP {rf.average_precision.mean():.4f}. The seed-17 operating threshold is {primary.threshold:.6f}, chosen on validation. Its source test contains {int(primary.tp):,} true positives, {int(primary.fn):,} false negatives, {int(primary.fp):,} false positives and {int(primary.tn):,} true negatives. The domain-bootstrap F1 interval is [{source_ci["f1"]["lower"]:.4f}, {source_ci["f1"]["upper"]:.4f}]. The two additional split seeds give F1 '+', '.join(f(v) for v in pd.read_csv(R/'split_sensitivity.csv').f1)+'. These values remain within the same collection and do not establish transfer to another source.')
p('Figure 4-1 uses actual saved predictions. The full-range panel makes the near-perfect source ranking visible; the expanded panel reveals differences that were obscured at that scale. Both panels use empirical steps and distinct line styles. Dots indicate the validation-selected operating points. The prevalence line explains the all-positive endpoint: with every URL labelled phishing by the decision rule, precision equals the test phishing fraction. An independently calculated AP matches the reported value. The high source scores and abrupt endpoint follow from the observed score distribution. Their numerical consistency does not establish external generalisation.')
fig('figure_4_1_source_pr.png','Figure 4-1. Source-test precision–recall curves for seed 17. Panel (a) shows the full range and class-prevalence baseline; panel (b) expands the high-score region. Dots mark validation-selected thresholds. Both panels use the same observed predictions.')
h('4.3 Frozen External Validation')
table('Table 4-2. Frozen-forest performance on the external holdout.', ['Variant','F1','AP','Recall','FPR'],[['Full 30 features',f(full.f1.mean()),f(full.average_precision.mean()),f(full.recall.mean()),f(full.false_positive_rate.mean())],['Seven host features',f(host.f1.mean()),f(host.average_precision.mean()),f(host.recall.mean()),f(host.false_positive_rate.mean())]],[2.1,.9,.9,.9,.9])
p(f'On the external holdout, the source-trained full forest gives mean F1 {full.f1.mean():.4f}, AP {full.average_precision.mean():.4f} and false-positive rate {full.false_positive_rate.mean():.4f}. It detects most labelled phishing examples by predicting phishing for almost all records, including legitimate ones. This is a substantive generalisation failure. Its AP is below the external positive prevalence {hold["phishing"]/hold["n"]:.4f}, so the failure cannot be explained solely by an unsuitable threshold. The source-trained ranking itself transfers poorly to this restricted external population.')
p(f'The primary full model’s external domain-bootstrap intervals are [{external_ci["f1"]["lower"]:.4f}, {external_ci["f1"]["upper"]:.4f}] for F1, [{external_ci["average_precision"]["lower"]:.4f}, {external_ci["average_precision"]["upper"]:.4f}] for AP and [{external_ci["false_positive_rate"]["lower"]:.4f}, {external_ci["false_positive_rate"]["upper"]:.4f}] for false-positive rate. The mean domain-macro legitimate recall is {full.macro_domain_legitimate_recall.mean():.4f}. Hence the poor legitimate detection is also present when each legitimate domain receives equal weight, rather than arising only from one high-volume domain.')
p(f'The host-only diagnostic improves external F1 to {host.f1.mean():.4f} and AP to {host.average_precision.mean():.4f}, but its false-positive rate remains {host.false_positive_rate.mean():.4f}. Its domain-macro legitimate recall is {host.macro_domain_legitimate_recall.mean():.4f}, lower than its row-weighted legitimate recall. This difference illustrates the effect of domain concentration. The diagnostic does not provide an operationally reliable replacement and is reported alongside the frozen full-model failure.')
fig('figure_4_2_external_pr.png','Figure 4-2. External-holdout precision–recall curves for the frozen seed-17 forests. Threshold dots retain source-validation choices. The external prevalence differs from the source-test prevalence, so AP values must be interpreted within their respective populations.')
h('4.4 Explanation and Source-Bias Diagnostics')
p(f'TreeSHAP identifies HTTPS, slash count and path length among the largest source-model contributions. The 160-example explanation batch reconstructs the model scores with maximum residual {ex["max_additivity_error"]:.2e}. It takes {ex["seconds"]:.3f} seconds excluding explainer construction, or {ex["seconds_per_explanation"]*1000:.2f} ms per explained observation averaged over this batch. These are local execution timings rather than deployed latency measurements.')
fig('figure_4_3_shap.png','Figure 4-3. Mean absolute phishing-score SHAP contributions on 160 source-test observations, using 80 source-training background examples.')
p(f'On the shared 60-example subset, aggregate importance rank correlations with the primary model are {ex["stability"][0]["spearman_global"]:.4f} and {ex["stability"][1]["spearman_global"]:.4f}; top-five overlaps are {ex["stability"][0]["top5_overlap"]:.2f} and {ex["stability"][1]["top5_overlap"]:.2f}. These repeatable rankings can still describe a poor external detector. Stability of an attribution does not establish that the underlying cue is valid in another population.')
p('The source audit finds that all 134,850 retained legitimate URLs use HTTPS and have empty paths. Among retained phishing URLs, 51,623 are non-HTTPS and 48,679 are HTTPS. The external holdout has a very different legitimate-path distribution. The combined evidence supports the interpretation that the source detector has learned collection-specific relationships. SHAP identifies reliance, the raw-data audit identifies the association, and the frozen external result shows failed transfer. This combination is stronger than inferring bias from a single feature-importance chart, but it still does not prove a unique causal explanation for every error.')
table('Table 4-3. Exploratory source-holdout feature ablations.', ['Feature set','Mean F1','Mean AP','Mean FPR'],[['Full 30 features',f(rf.f1.mean()),f(rf.average_precision.mean()),f(rf.false_positive_rate.mean())]]+[[{'without_https':'Without HTTPS flag','host_only':'Seven host features','https_only':'HTTPS flag only'}[v],f(g.f1.mean()),f(g.average_precision.mean()),f(g.false_positive_rate.mean())] for v,g in ab.groupby('variant',sort=False)],[2.4,1.1,1.1,1.1])
p('Removing the HTTPS flag reduces source performance, and restricting the representation to host features reduces it further. Removing one flag does not remove correlated path and length information. These ablations were designed after observing source results and are labelled exploratory. No claim of an independently confirmed feature-selection improvement is made. Their role is to expose dependence and to motivate better data collection.')
fig('figure_4_6_ablation.png','Figure 4-4. Exploratory source-holdout F1 under restricted feature sets. These diagnostic variants reuse the source holdout and do not constitute independent confirmatory experiments.')
h('4.5 Adaptive Replay Results')
table('Table 4-4. Source-switch replay means across three paired realizations.', ['Delay','Policy','Overall F1','Target F1','Overall FPR','Refits'],[[str(d),{'fixed':'Fixed','periodic':'Periodic','drift':'ADWIN','threshold':'Threshold'}[policy],f(a(d,policy,'f1')),f(a(d,policy,'phase_B_f1')),f(a(d,policy,'false_positive_rate')),str(round(a(d,policy,'updates')))] for d in [0,2] for policy in ['fixed','periodic','drift','threshold']],[.6,1.05,1.1,1.0,1.15,.8])
p(f'With immediate batch feedback, periodic updating achieves mean overall F1 {a(0,"periodic","f1"):.4f}, compared with {a(0,"drift","f1"):.4f} for ADWIN and {a(0,"fixed","f1"):.4f} for the fixed forest. Their target-segment F1 values are {a(0,"periodic","phase_B_f1"):.4f}, {a(0,"drift","phase_B_f1"):.4f} and {a(0,"fixed","phase_B_f1"):.4f}. Thus ADWIN saves updates but performs worse than periodic refitting in the tested source switch. The revised evidence does not support a claim that their detection performance is equivalent.')
p(f'The threshold-only policy gives overall F1 {a(0,"threshold","f1"):.4f} with immediate feedback and {a(2,"threshold","f1"):.4f} with delayed feedback. It does not recover the benefit of retraining. This is consistent with the poor cross-corpus ranking result: adjusting a cutoff has limited value when legitimate and phishing scores are poorly ordered. The conclusion is restricted to this learner, representation and calibration-window rule.')
fig('figure_4_4_source_replay.png','Figure 4-5. Source-switch batch F1 aligned to each realization’s designed boundary. Lines are three-run means and shading is one standard deviation, not a confidence interval. Only relative positions observed in all three realizations are shown.')
p(f'At delay two, periodic and ADWIN overall F1 fall to {a(2,"periodic","f1"):.4f} and {a(2,"drift","f1"):.4f}. Each ADWIN realization uses one forest refit. The revised detector ignores 800 delayed error values from older prediction versions after that refit, while retaining their labels for the training window. The first version admitted those values into a reset detector; the new call-site test fails on that behaviour and passes after the correction. All original predictions, including those whose feedback is excluded from detection, remain in the performance score.')
table('Table 4-5. Stationary-mixture control means.', ['Delay','Policy','F1','FPR','Refits'],[[str(d),{'fixed':'Fixed','periodic':'Periodic','drift':'ADWIN','threshold':'Threshold'}[policy],f(a(d,policy,'f1','stationary_mixture')),f(a(d,policy,'false_positive_rate','stationary_mixture')),str(round(a(d,policy,'updates','stationary_mixture')))] for d in [0,2] for policy in ['fixed','periodic','drift','threshold']],[.65,1.5,1.2,1.2,1.15])
p('No ADWIN refit occurs in any of the six stationary-mixture runs, and its predictions therefore match the fixed policy. Periodic refitting still improves mean F1 modestly, indicating that additional labelled data can help even without an alarm. Six no-alarm observations do not estimate a universal false-alarm probability. This control provides evidence for the specific replay lengths, draws and detector settings.')
fig('figure_4_5_update_cost.png','Figure 4-6. Source-switch forest refits and total forest fitting time, averaged over three runs. The threshold-only policy changes cutoffs without refitting. Fitting time excludes detection, calibration, prediction and checkpoint persistence.')
p(f'Immediate-label periodic and ADWIN fitting times average {a(0,"periodic","total_fit_seconds"):.3f} s and {a(0,"drift","total_fit_seconds"):.3f} s, including the initial fit. Their update counts are seven and one. Under delayed feedback the corresponding times are {a(2,"periodic","total_fit_seconds"):.3f} s and {a(2,"drift","total_fit_seconds"):.3f} s, with six and one refits. The lower ADWIN fitting cost accompanies lower detection performance, so these measurements represent a tradeoff. They do not justify an unmeasured total-system speedup or a preferred deployment operating point.')
h('4.6 Project Management and Reproducibility')
p(f'The accepted archive {args.run_id} retains executed conditions, model checkpoints and the measurements used to generate the result tables and figures. Separate archives preserve the earlier draft, delayed-feedback defect and first revision runner’s finalisation error for review. Acquisition metadata retain dataset licences and attribution records.')
p('The project delivers source code, dependency specifications, configuration snapshots, data provenance, numerical results, figures and this report. Further research requires timestamped feedback, additional validation sources and a representation less dependent on the identified collection cues. These tasks remain uncompleted.')
h('4.7 Discussion and Threats to Validity')
p('The source and external results show that domain isolation is necessary for the chosen identity boundary but insufficient for collection-level generalisation. The source forest’s high AP is numerically reproducible, yet its external AP is lower than the external prevalence baseline. Describing the source plot alone as evidence of robust phishing detection would therefore be misleading. The external failure is a principal finding of this study.')
p('The replay experiment offers a narrower positive result: when labels from a changed source are available, forest refitting improves later decisions relative to the initial source-only forest. Periodic updating performs best among the tested policies, while ADWIN reduces the number of refits and avoids refitting in the stationary control. The source boundaries, balanced class sampling, limited set of settings and repeated target domains constrain that interpretation. Natural-time data, real annotation costs and operational class prevalence may produce different results.')
p('Other threats include unverified published labels, feature correlations, only two corpora, one primary source split, a small explanation sample and repeated use of source holdouts for exploratory diagnostics. The external holdout contains many legitimate rows from relatively few domains, motivating the reported domain-weighted checks but not eliminating selection bias. The initial source corpus and the target corpus also share public-feed provenance. Domain exclusions reduce observed overlap, but cannot prove complete independence of campaigns or collection practices.')

h('Chapter 5. Conclusion',1)
h('5.1 Summary')
p(f'For RQ1, the full forest reaches source F1 {rf.f1.mean():.4f}, but frozen external F1 is {full.f1.mean():.4f} with false-positive rate {full.false_positive_rate.mean():.4f}. This is strong evidence against treating the source benchmark score as operational reliability. The source PR curve was independently reconstructed, and its scale now displays the differences between models without changing the underlying observations.')
p('For RQ2, TreeSHAP provides numerically additive and locally repeatable aggregate attributions. Combined with the raw-data audit and exploratory ablations, it identifies dependence on scheme and path conventions. Repeatability is compatible with a consistently biased predictor. The study does not claim a causal explanation or demonstrated improvement in user trust.')
p(f'For RQ3, periodic refitting achieves source-switch overall F1 {a(0,"periodic","f1"):.4f} under immediate feedback, above ADWIN’s {a(0,"drift","f1"):.4f}, while requiring more refits. Both outperform the fixed initial forest and the threshold-only comparator. Delayed feedback reduces performance. The corrected model-version rule prevents stale errors from contaminating the reset detector. No ADWIN updates occur in the six stationary-mixture controls. These are results from controlled replays of real records, not observations of natural calendar-time drift.')
h('5.2 Contributions and Limitations')
p('The contribution is an auditable empirical evaluation linking explainability, external failure and adaptive-update tradeoffs. The implementation retains published inputs, documents exclusions, separates external holdout and adaptation domains, freezes external thresholds, tracks delayed feedback by prediction version, and preserves model checkpoints and original predictions. The reported negative findings are as important as the within-corpus and replay improvements.')
p('The detector remains unsuitable for deployment on the strength of these results. Source bias, the limited corpora, artificial replay ordering, balanced segment sampling, target-domain recurrence and unverified annotation quality prevent a broad effectiveness claim. A statistical superiority claim would require a design that accounts for these dependencies and a wider set of independent sources and time periods. The existing evidence supports the stated experimental conditions only.')
h('5.3 Future Work')
p('The next priority is a dataset with observation and label-verification timestamps, realistic legitimate paths and documented acquisition practices. A chronological test should retain the prediction-time feature contract and reveal labels at recorded availability times. Further source-balanced training, model calibration, alternative representations and budget-matched update policies could test whether the external failure can be reduced without excessive false positives.')
p('Explanation work should examine background sensitivity, correlated feature families and successive adaptive checkpoints on a common reference set. A human study would be required to assess understanding or trust. These extensions should be specified before evaluating an untouched holdout, with failed as well as successful conditions retained. The current project provides a reproducible basis for that work rather than evidence that these extensions have already succeeded.')

# First-appearance numeric order for the temporary review manuscript.
# These are intentionally not fabricated Mendeley Cite fields.
refs=json.loads((ROOT/'docs/references.json').read_text());lookup={r['number']:r for r in refs};order=[]
for b in blocks:
    strings=[b.get('text',''),b.get('caption','')]+[str(x) for row in b.get('rows',[]) for x in row]
    for text in strings:
        for n in re.findall(r'\[(\d+)\]',text):
            if int(n) not in order:order.append(int(n))
mapping={old:i+1 for i,old in enumerate(order)}
def renumber(text):return re.sub(r'\[(\d+)\]',lambda m:'['+str(mapping[int(m.group(1))])+']',text)
for b in blocks:
    for k in ['text','caption']:
        if k in b:b[k]=renumber(b[k])
    if b['type']=='table':b['rows']=[[renumber(str(v)) for v in row] for row in b['rows']]
def reference(r,num):
    authors=', '.join(r['authors']) if len(r['authors'])<=6 else r['authors'][0]+' et al.'
    s=f'[{num}] {authors}, “{r["title"]},” {r["venue"]}'
    for key,label in [('volume','vol.'),('issue','no.'),('pages','pp.'),('article_number','Art. no.'),('version','V')]:
        if r.get(key):s+=f', {label} {r[key]}'
    if r.get('year'):s+=f', {r["year"]}'
    if r.get('doi'):s+=f', doi: {r["doi"]}.'
    else:
        accessed=date.fromisoformat(r.get('accessed','2026-10-01')).strftime('%-d %B %Y')
        s+=f'. [Online]. Available: {r["url"]}. Accessed: {accessed}.'
    return s
h('References',1)
for old in order:blocks.append({'type':'reference','text':reference(lookup[old],mapping[old])})
doc={'title':'Explainable and Adaptive Machine Learning for Phishing Detection','author':'Geoff','student_id':'202318020401','major':'Software Engineering','supervisor':'Collins Sey','draft_date':'6 October 2026','status':'Revised draft','run_id':args.run_id,'citation_integration':'NOT_MENDELEY_CITE_LINKED; account/add-in unavailable; numeric citations are temporary review references','blocks':blocks,'citation_mapping':mapping}
(BUILD/'manuscript.json').write_text(json.dumps(doc,indent=2,ensure_ascii=False))
md=['# '+doc['title'],'','Author: Geoff. Revised 6 October 2026.','', '> Citation integration status: temporary review citations; Mendeley Cite linkage is pending an authenticated add-in session.','']
for b in blocks:
    if b['type']=='heading':md.append('#'*b['level']+' '+b['text'])
    elif b['type'] in ['paragraph','reference']:md.append(b['text'])
    elif b['type']=='equation':md.extend(['$$',(ROOT/'thesis/equations'/f'eq_{b["number"]}.tex').read_text().strip()+r'\tag{'+b['number']+'}','$$'])
    elif b['type']=='figure':md.append('!['+b['caption']+']('+b['path']+')')
    elif b['type']=='table':md.extend([b['caption'],'| '+' | '.join(b['headers'])+' |','| '+' | '.join(['---']*len(b['headers']))+' |']+['| '+' | '.join(row)+' |' for row in b['rows']])
    md.append('')
(ROOT/'thesis/revised_manuscript.md').write_text('\n'.join(md))
words=sum(len(re.findall(r'\b[\w’-]+\b',b.get('text',''))) for b in blocks if b['type']=='paragraph')
(BUILD/'manuscript_stats.json').write_text(json.dumps({'prose_words':words,'figures':sum(b['type']=='figure' for b in blocks),'tables':sum(b['type']=='table' for b in blocks),'references':len(order),'equations':sum(b['type']=='equation' for b in blocks)},indent=2))
locations=[];section='';by_new={mapping[old]:lookup[old] for old in order}
for i,b in enumerate(blocks):
    if b['type']=='heading':section=b['text']
    if b['type']=='reference':continue
    text=' '.join([b.get('text',''),b.get('caption','')]+[str(x) for row in b.get('rows',[]) for x in row]).strip()
    numbers=list(dict.fromkeys(int(n) for n in re.findall(r'\[(\d+)\]',text)))
    if numbers:
        locations.append({'block_index':i,'section':section,'text':text,'temporary_numbers':numbers,'mendeley_lookup_keys':[{'key':by_new[n]['id'],'title':by_new[n]['title'],'doi':by_new[n].get('doi')} for n in numbers]})
(ROOT/'references/citation_locations.json').write_text(json.dumps({'status':'temporary review references; not Mendeley Cite controls','locations':locations},indent=2,ensure_ascii=False))
print('Revised manuscript:',words,'prose words,',len(order),'references')
